/**
 * Copyright 2022-2023 Charles Coughlin. All Rights Reserved.
 * MIT License.
 */
package chuckcoughlin.bert.command.controller

import chuckcoughlin.bert.common.controller.Controller
import chuckcoughlin.bert.common.controller.ControllerType
import chuckcoughlin.bert.common.controller.NamedSocket
import chuckcoughlin.bert.common.message.CommandType
import chuckcoughlin.bert.common.message.MessageBottle
import chuckcoughlin.bert.common.message.RequestType
import chuckcoughlin.bert.common.model.ConfigurationConstants
import chuckcoughlin.bert.common.model.RobotModel
import chuckcoughlin.bert.speech.process.MessageTranslator
import chuckcoughlin.bert.sql.db.Database
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.MainScope
import kotlinx.coroutines.async
import kotlinx.coroutines.cancel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.selects.select
import java.util.logging.Logger

/**
 * This is the class that handles spoken commands and forwards
 * them on to the central dispatcher. It also handles database actions
 * involving playback and record.
 *
 * This class routes requests/responses between the Dispatcher and "blueserverd" daemon.
 * Communication with the Dispatcher is via Kotlin channels and communication with
 * Bluetooth is via a socket.
 *
 * @param parent - the dispatcher
 * @param req - channel for dispatcher requests as generated by the user
 * @param rsp - channel for responses from the parent (Dispatcher)
 */
class Command(parent: Controller,req : Channel<MessageBottle>,rsp: Channel<MessageBottle>) :Controller {
    private var tabletSocket: BluetoothSocket
    private val messageTranslator: MessageTranslator
    private val dispatcher = parent
    private var requestChannel  = req    // Dispatcher->Command  (results of user requests)
    private var responseChannel = rsp    // Command->Dispatcher  (requests initiated by user)

    private val scope = MainScope() // Uses Dispatchers.Main
    private var ignoring : Boolean
    private var running:Boolean

    /**
     * While running, read from the bluetooth daemon (representing the tablet) and forward
     * resulting requests to the dispatcher. We accept its responses and forward back to the tablet.
     * Communication with the tablet consists of simple strings, plus a 4-character header.
     *
     * A few messages are intercepted that cause a quick shutdown. These are direct responses
     * to user input, like "shutdown".
     */
    override suspend fun start() {
        if( !running ) {
            running = true
            runBlocking<Unit> {
                launch {
                    Dispatchers.IO
                    while (running) {
                        select<Unit> {
                            /**
                             * These are responses coming from the Dispatcher
                             * Send them to the Bluetooth socket
                             */
                            responseChannel.onReceive() {
                                tabletSocket.receiveResponse(it)   // stdOut
                            }
                            /**
                             * Read from bluetooth, blocked. Use ANTLR to convert text into requests.
                             * Forward requests to the Terminal launcher.
                             */
                            async {
                                val msg = tabletSocket.receiveRequest()
                                if (isLocalRequest(msg)) {
                                    handleLocalRequest(msg)
                                }
                                else {
                                    requestChannel.send(msg)
                                }
                            }
                        }
                    }
                }
            }
        }
        else {
            LOGGER.warning(String.format("%s: attempted to start, but already running...", CLSS))
        }
    }

    override suspend fun stop() {
        if( running ) {
            running = false
            scope.cancel()
            Database.shutdown()
            LOGGER.warning(String.format("%s: exiting...", CLSS))
            System.exit(0)
        }
    }


    // We handle the command to sleep and awake immediately.
    private fun handleLocalRequest(request: MessageBottle): MessageBottle {
        if (request.type.equals(RequestType.COMMAND)) {
            val command: CommandType = request.command
            LOGGER.warning(String.format("%s.handleLocalRequest: command=%s", CLSS, command))
            if( command.equals(CommandType.SLEEP) ) {
                ignoring = true
            }
            else if( command.equals(CommandType.WAKE) ) {
                ignoring = false
            }
            else {
                val msg = String.format("I don't recognize command %s", command)
                request.error = msg
            }
        }
        request.text = messageTranslator.randomAcknowledgement()
        return request
    }

    // Local requests are those that can be handled immediately without forwarding to the dispatcher.
    private fun isLocalRequest(request: MessageBottle): Boolean {
        if (request.type.equals(RequestType.COMMAND)) {
            val cmd = request.command
            if (cmd == CommandType.SLEEP || cmd == CommandType.WAKE) {
                return true
            }
        }
        return false
    }

    private val CLSS = "Command"
    private val LOGGER = Logger.getLogger(CLSS)
    private val EXIT_WAIT_INTERVAL: Long = 1000
    override var controllerName = CLSS

    init {
        controllerName = RobotModel.getControllerForType(ControllerType.COMMAND)
        ignoring = false
        running = false
        messageTranslator = MessageTranslator()
        val socketName = RobotModel.getPropertyForController(controllerName, ConfigurationConstants.PROPERTY_SOCKET)
        val port = RobotModel.getPropertyForController(controllerName, ConfigurationConstants.PROPERTY_PORT).toInt()
        val socket = NamedSocket(socketName,port)
        tabletSocket = BluetoothSocket(socket)
    }
}