#!/bin/sh
# Execute the robot control code in "offline" mode on the test system.
# Bluetooth and serial port features do not work.
# Clear logs first
cd ${BERT_HOME}
bin/clear_logs
cd distribution/bertApp
export APP_HOME=`pwd`
cd bin
./bertApp -o ${BERT_HOME}