#!/bin/bash
# DO NOT run this script as root.
# Synchronize the robot with the current build products.
# The 'rsync' command is an efficient way to guarantee
# that no more files are transferred than necessary.
# Make sure there is a valid wi-fi connection. If the
# init scripts have changed their install scripts must be
# on the target system (with sudo)
ROBOT_HOME=/usr/local/robot
export PATH=$PATH:/usr/local/bin
echo "Synchronizing configuration files, database ..."
cd ${BERT_HOME}
rsync -r etc bin csv sql  pylib bert:${ROBOT_HOME}

echo "Synchronizing the distribution area ..."
cd ${BERT_HOME}
rsync -r distribution bert:${ROBOT_HOME}

echo "Robot update is complete."
