/*
 * By convention buildSrc is built first and defines conventions used
 * by the remaining modules.
 * This file was generated by the Gradle 'init' task.
 * and uses @Incubating APIs which are subject to change.
 */

// Support convention plugins written in Kotlin. Convention plugins are build scripts
// in 'src/main' that automatically become available as plugins in the main build.
plugins {
    `kotlin-dsl`
}

// Use the plugin portal to apply community plugins in convention plugins.
repositories {
    gradlePluginPortal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin")
}
