/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chuckcoughlin.bert

class App {
    val greeting: String
        get() {
            return "Hello World #1"
        }
}

fun main() {
    println(App().greeting)
}
